### ISSUE TITLE
Create Solution for Keying Proposals to DAOs

### ISSUE THREAD

**Issue by R-K-H** [metaDAOproject/futarchy#106]
Currently the multi-DAO system affords flexibility for creation of DAOs under one program. This is great and can be SOMEWHAT easily supported in the UI, however tracing proposals ownership is not intuitive.

Under current design schema one would have to trace a proposal through its base and quote vaults to match on a DAO. And requires fetching the DAOs to do so.

A proposed solution is to key the proposal to the DAO is some form or fashion.

**Comment by Henry-E** [comment]
Possible solution, make proposal account into a PDA that takes the DAO pubkey and proposal number as seeds?
https://github.com/metaDAOproject/futarchy/blob/0bb2ee53f393b1491ccce32a46f954d7563f3892/programs/autocrat_v0/src/lib.rs#L449

**Comment by metaproph3t** [comment]
I think I'm just going to do the quick & dirty solution, which is add `dao` to the `Proposal` struct

**Comment by metaproph3t** [comment]
Addressed via #110
