### ISSUE TITLE
Review And Audit Autocrat, AMM, TWAP, Conditional Vault V1.0

### ISSUE THREAD

**Issue by R-K-H** [metaDAOproject/futarchy#170]

**Comment by Henry-E** [comment]
I'm in the process of using some of the programs but I'm probably not going to do a proper end-to-end audit like robre or something. I'll just be reviewing as I go through using it and see if anything crops up. So just moving this to `done` essentially but it'll still be an ongoing thing anyway.

**Comment by R-K-H** [comment]
Thanks for the update.
