### ISSUE TITLE
Deploy 3 DAOs & proposals on devnet for 1.0.0

### ISSUE THREAD

**Issue by metaproph3t** [metaDAOproject/futarchy#176]
Deploy the three DAOs on devnet corresponding to MetaDAO, Dean's List, and Future DAO.

Also attach a proposal to each of them.

**Comment by R-K-H** [comment]
Sorry this needs to be more than 3...

- Deans List
- Ore
- Dark
- Future
- MetaDAO

Will contact Drift to see.

**Comment by R-K-H** [comment]
I'll split off another ticket after I've reviewed this.
