### ISSUE TITLE
Enable multiple DAO instantiations

### ISSUE THREAD

**Issue by Dodecahedr0x** [metaDAOproject/futarchy#18]
Currently, the DAO is global for the program. It simplifies some parts of the code but it makes it more expensive to create new DAO instances because you need to redeploy the program. Enabling multiple instances makes it more affordable for everyone to experiment with futarchy. It could also open the door for DAO merging and forking, which might prove helpful.

**Comment by metaproph3t** [comment]
Yeah, I agree that this would be a useful feature

At the moment, I prefer that we keep it as it is in order to minimize the attack / bug surface (e.g., a bug could be a mismatch between a DAO and some vault account), but definitely this could be something worth upgrading to

**Comment by metaproph3t** [comment]
This has been done
