### ISSUE TITLE
Create DAOs & Proposals On Devnet

### ISSUE THREAD

**Issue by R-K-H** [metaDAOproject/futarchy#186]
Need the following:

- [x] Dark (Needs token with metadata)
- [x] Ore (Needs token with metadata)
- [x] Drift (Needs token with metadata)

You can use https://metaboss.rs/ to create these tokens and update the data. Let me know if you need support or can't get to this.

**Comment by R-K-H** [comment]
Dark
![3VPYgJz-wlRAm1H5_4zrsAckyz55qa5ILyk3Uq6l4Ms](https://github.com/metaDAOproject/futarchy/assets/1007667/167663fd-b5a8-448a-a256-947a2e94022f)

https://solscan.io/token/FmQ7v2QUqXVVtAXkngBh3Mwx7s3mKT55nQ5Z673dURYS

```json
{
  "key": 4,
  "updateAuthority": "FDfhQ9t7Nq8U4Y2xXynmd9bQW8HMdgbVS5PggeuAaff3",
  "mint": "FmQ7v2QUqXVVtAXkngBh3Mwx7s3mKT55nQ5Z673dURYS",
  "data": {
    "name": "Dark Protocol",
    "symbol": "DARK",
    "uri": "https://arweave.net/EtLH9bBZdhhs9OFkntBPvQBW8r_TNBouOom4yJctcbI",
    "sellerFeeBasisPoints": 0
  },
  "primarySaleHappened": 0,
  "isMutable": 1,
  "editionNonce": 255,
  "tokenStandard": 2
}
```

```json
{
  "name": "Dark Protocol",
  "symbol": "DARK",
  "description": "Dark Token is the Native Ecosystem token of 'Dark Protocol' - A DAO Governed Privacy-as-a-Service (PaaS) Protocol.",
  "seller_fee_basis_points": 0,
  "image": "https://www.arweave.net/3VPYgJz-wlRAm1H5_4zrsAckyz55qa5ILyk3Uq6l4Ms?ext=png",
  "external_url": "",
  "properties": {
    "category": "image",
    "files": [
      {}
    ]
  }
}
```

**Comment by R-K-H** [comment]
Ore

![icon](https://github.com/metaDAOproject/futarchy/assets/1007667/5cc5784f-d8ee-4a76-b05e-6703f1ffa98a)

https://solscan.io/token/oreoN2tQbHXVaZsr3pf66A48miqcBXCDJozganhEJgz#metadata

```json
{
  "key": 4,
  "updateAuthority": "tHCCE3KWKx8i8cDjX2DQ3Z7EMJkScAVwkfxdWz8SqgP",
  "mint": "oreoN2tQbHXVaZsr3pf66A48miqcBXCDJozganhEJgz",
  "data": {
    "name": "Ore",
    "symbol": "ORE",
    "uri": "https://ore.supply/metadata.json",
    "sellerFeeBasisPoints": 0
  },
  "primarySaleHappened": 0,
  "isMutable": 1,
  "editionNonce": 253,
  "tokenStandard": 2
}
```

```json
{
  "name": "Ore",
  "image": "https://ore.supply/icon.png",
  "symbol": "ORE",
  "description": "Ore is a cryptocurrency you can mine from anywhere, at home or on your phone.",
  "twitter": "https://x.com/oresupply",
  "website": "https://ore.supply"
}
```

**Comment by R-K-H** [comment]
Drift

![drift-logo](https://github.com/metaDAOproject/futarchy/assets/1007667/c6f52d14-5c10-4f70-b6a1-78d374773407)

From the party: `There’s no devnet token currently, but 6 decimals is expected`

**Comment by metaproph3t** [comment]
ORE: Et9wvs9gEBQtFY2RkvLw2XVLaBqjotHPvQBDvqkKxDR8

**Comment by metaproph3t** [comment]
DARK: FfCGxfj1NQdPZpukoEgdX427NEjNdCuh3gpFi6oEf6Ka

**Comment by metaproph3t** [comment]
Drift: Hy9aVik24Uy92FuJd8d1hTH6LRCLmquipeTLBGnXqWr1
