### ISSUE TITLE
Create Devnet Dark Token And Issue To Developers

### ISSUE THREAD

**Issue by R-K-H** [metaDAOproject/futarchy#195]
Dark has said they just want us to generate the token, so we should and then setup a DAO, same thing with Ore and Drift.

Ore he MAY have sent them, I'm happy to support with images and details if necessary. Also feel free to reassign if not able to not worth the time.

So ore did create some tokens 
https://solscan.io/token/AWySaxJ3TioSPyc8NP3gDw4vg4jrHAHqYpCCvx6gJoin?cluster=devnet#metadata

However they're missing metadata so we may just create our own to more accurately mimic mainnet.

**Comment by R-K-H** [comment]
`7gvWPvzqQhNJnmqFq7C8bg6GGtAWj6RaegC2NQscGqrg`
`7HWGTDdB7T6QnGn11mE7mKFohQfLkeyLpzTALHD7FWdW`
`Fd4A7Kb1JyS1QJ8wZa9Bw6n5ydjLDNHf7xjXeVxC3L6m`
`CRANkLNAUCPFapK5zpc1BvXA1WjfZpo6wEmssyECxuxf`
`HwBL75xHHKcXSMNcctq3UqWaEJPDWVQz6NazZJNjWaQc`
`HfFi634cyurmVVDr9frwu4MjGLJzz9XbAJz981HdVaNz`
`49G96gYpqEsU1icjoVf45yi7o4CqA33y8jFgiZUzoVx5`

**Comment by metaproph3t** [comment]
Send devnet META
