### ISSUE TITLE
Conditional vault operations should include the mint

### ISSUE THREAD

**Issue by Dodecahedr0x** [metaDAOproject/futarchy#27]
Minting conditional token currently does not use the Mint account of the token deposited. This is possible because the mint is stored by the vault and token accounts do not explicitly require the mint.

However, this prevents indexer from noticing the transactions and tools like Dune to correctly index transactions.
Including the mint in the transaction could simplify some security checks by only checking the mint instead of checking the underlying mint + underlying account ([here](https://github.com/metaDAOproject/meta-dao/blob/c88a8605cdc0d2ece4dcb25d6a0c3a89bbf7c79b/programs/conditional_vault/src/lib.rs#L423) and [here](https://github.com/metaDAOproject/meta-dao/blob/c88a8605cdc0d2ece4dcb25d6a0c3a89bbf7c79b/programs/conditional_vault/src/lib.rs#L442)). It could also save account space by only storing the mint and deriving the accounts

**Comment by metaproph3t** [comment]
yep, agree this should be added, maybe not in this current iteration (trying to do the minimum viable change, just stuff related to parameters) but in next one
