### ISSUE TITLE
make conditions for finalizing a proposal more robust

### ISSUE THREAD

**Issue by 0xbigz** [metaDAOproject/futarchy#28]
currently only twaps need to be higher by threshold for proposal to pass. just relying on the twaps as currently implemented might be too easy to game.

i wonder if its better to also ensure that
1. mid price (and/or bid, ask) of the market is **consistent** with the twap differences (including threshold?)
2. allow way to pay to extend proposal (opposite to fee cooldown to launch a new proposal?) 

this consistency check wouldn't change whether a proposal passes or not, but just delays finalizing. this gives ample time to for those who really disagree with a proposal to exit before it's allowed to pass.

https://github.com/metaDAOproject/meta-dao/blob/c88a8605cdc0d2ece4dcb25d6a0c3a89bbf7c79b/programs/autocrat_v0/src/lib.rs#L328

**Comment by metaproph3t** [comment]
> mid price (and/or bid, ask) of the market is consistent with the twap differences (including threshold?)

what does it mean for it to be consistent?

> this gives ample time to for those who really disagree with a proposal to exit before it's allowed to pass.

I feel like the exit mechanism is the conditional-on-pass market - you can dump your META in the conditional-on-pass market so that you're guaranteed that you will have sold if it passes

**Comment by 0xbigz** [comment]
lets say pass twap > fail twap
but current fail mid > pass mid

that likely means there are trades that should be cleared before finalizing

because of spreads and market condition evolution in the above scenario is quite likely. basically someone didnt have a chance to sell until closer to the very end, but missed out

**Comment by metaproph3t** [comment]
Replaced with #59
