### ISSUE TITLE
Rebate taker fees to people who traded in the unfinalized market

### ISSUE THREAD

**Issue by metaproph3t** [metaDAOproject/futarchy#31]
Ideally, we'd have an incentive to trade in markets up until the very end, to allow for better price discovery. We could rebate taker fees to people who traded in the unfinalized market, as discussed in #26

**Comment by 0xbigz** [comment]
more specifically, i think you want to reward proportionately realized pnl at termination.

to calculate, compare net deposited META/USDC to redeemed. perhaps 'settle' (p/f)META to mid or twap price

**Comment by metaproph3t** [comment]
I'm no longer sold that this is helpful for price discovery, and I have yet to see something that rewards volume that is resistant to wash trading

closing for now
