### ISSUE TITLE
Add ability to redeem 1:1 p-f tokens into their underlying while proposal is active

### ISSUE THREAD

**Issue by R-K-H** [metaDAOproject/futarchy#35]
This would afford better price discovery and more competitive marketing. I've thought about this and the only potential thoughts I have with respect to that are:

1. It puts more price pressure on the market such that increasing value by 5% may be extremely challenging.
2. Capital flight from proposal, such that limit order books become thin and may prevent TWAP from registering.
3. Predatory poaching of order books such that money cycles through different proposals but doesn't really effectively provide insight.

On the other side of it, it would allow for multiple proposals to be ongoing at once, where currently you really are limited by the amount of capital you want to allocate where and for how long. It's concerning that you couldn't have multiple and expect full participation from all participants within the ecosystem.

**Comment by R-K-H** [comment]
Could you restrict who can deposit p/f tokens into contracts / proposals?

Such that you don't need more token, but you can only have an even weight to assets : liabilities?

It fractures liquidity still, but maintains token standardization.

**Comment by metaproph3t** [comment]
> Could you restrict who can deposit p/f tokens into contracts / proposals?
> 
> Such that you don't need more token, but you can only have an even weight to assets : liabilities?
> 
> It fractures liquidity still, but maintains token standardization.

What do you mean by 'deposit p/f tokens into contracts / proposals'?

I think of it as depositing META/USDC into the conditional vault in exchange for p / f tokens, and then trading p / f tokens in openbook

**Comment by R-K-H** [comment]
Yea, but the "market" is a contract. And what im saying is that if the market doesn't have enough assets to cover liabilities then the liabilities couldn't be deposited to open an order. Im not sure if this even makes sense outside of trying to standardize markets and tokens such that fractured liquidity isn't an issue.

**Comment by metaproph3t** [comment]
Replaced by #58
