### ISSUE TITLE
Add depth to TWAP calculation

### ISSUE THREAD

**Issue by 0xbigz** [metaDAOproject/futarchy#48]
given price volatility / supply can dilute, [relying on 1 META tick size isnt safety guarantee](https://twitter.com/MetaDAOProject/status/1759594121239425534)

[these notes](https://hackmd.io/@ansatz/metadao-prop0) also discussed issues around the impl of twap updates

i suggest depth param to be calc'd as some scaled clamped amount of p/f META/USDC in vault

ask depth:
`(p/fMETA.amount * x_scalar).clamp(x_1, x_2)`

bid depth:
`(p/fUSDC.amount* y_scalar).clamp(y_1, y_2)`

think something like scalar < 1 and > 0 and clamp up to ~ mid price * 10 could makes sense

**Comment by metaproph3t** [comment]
What's the point of doing it based on number of tokens in the vault? Suppose that there's 3,000 META in a vault. That doesn't give any information on what the price of META is, which is what's important for the tick size (it needs to be economically significant).

**Comment by metaproph3t** [comment]
Closing for now, I'm open to re-open
