### ISSUE TITLE
Expand program to support multi dao (ID)

### ISSUE THREAD

**Issue by R-K-H** [metaDAOproject/futarchy#75]
Revisions which need to address:
- [ ] Coupling with META token
- [ ] PDA w/ Seed
- [ ] Base unit logics (decimals with tokens)
- [ ] Interface with expansive capacity for iterations (metadata or config settings)

What I'm thinking here is if we want to test things is there a way to securely make changes which afford flexibility without arduous process. I understand this could be in conflict with security so not going to press that issue too much.

Say we'd like to build a proposal with three day see the response, then one day see the response, eventually resolving to a fixed code structure, or creation of structure supporting the results of our testing and evaluation.

For additional context: The question is where should default values of potentially adjustable values live? If you wanted to enforce PreTrading proposal state, but some didn't, or if you wanted to afford 1-10 day proposal time, or if you wanted to adjust minimum order size, or if you wanted to use AMM exclusively compared to hybrid, or only one instruction type.

Those questions exist for me, and the practicality of which are unknown.

**Comment by metaproph3t** [comment]
I've got some time today, going to try and bang this out
