### ISSUE TITLE
Include the USDC price of a coin when creating a DAO

### ISSUE THREAD

**Issue by Henry-E** [metaDAOproject/futarchy#92]
At least while we still use openbook and are opening up the metadao program to new DAOs, we can use the dollar value of a project's token to help determine the quote and lot sizes. 

Rough heuristic
- Base lot sizes should be adjusted so they correspond to a minimum of $1 worth of the token
- Double check that the quote lot size is not smaller than the price, it defaults to 100 quote lot size which should be small enough but you never know

With knowing the USDC value, this would also make it possible to set the expected value accurately and also set the max movement value of the TWAP, which is in terms of price lots (number of quote lots per 1 base lot), at 5% of the expected value.

Maybe because of variance encourage DAOs to put a smaller number than the true current dollar value.

**Comment by R-K-H** [comment]
This is now established in the initalizeDao. @metaproph3t could you confirm that indeed this is already handled. Or if this is in reference to a previous issue with order books.
