### ISSUE TITLE
Deploy Multi-DAO Program to Devnet

### ISSUE THREAD

**Issue by R-K-H** [metaDAOproject/futarchy#93]
To continue development we'll need programs deployed on Devnet. Included in this task is:

- [ ] Deploy program to devnet
- [ ] Include any scripts or instructions for interfaces

**Comment by Henry-E** [comment]
It's a bit messy but I wrote a deployment script to help with getting everything onto devnet and mainnet. It's only a step above just having a set of commands in a text file that you copy-paste and update addresses on but it helped me with deploying four verified programs and IDLs to devnet and mainnet.

 https://github.com/Henry-E/futarchy-deploy-scripts/

**Comment by metaproph3t** [comment]
> It's a bit messy but I wrote a deployment script to help with getting everything onto devnet and mainnet. It's only a step above just having a set of commands in a text file that you copy-paste and update addresses on but it helped me with deploying four verified programs and IDLs to devnet and mainnet.
> 
> https://github.com/Henry-E/futarchy-deploy-scripts/

cool, this is super helpful!

**Comment by metaproph3t** [comment]
Deployed: FuTPR6ScKMPHtZFwacq9qrtf9VjscawNEFTb2wSYr1gY

Branch (don't want to merge onto develop until we merge develop onto production): https://github.com/metaproph3t/futarchy/tree/multi-dao
